### ISSUE TITLE
Example not working: requires OAuth2?

### ISSUE THREAD

**Issue by opn** [audioBoom/audioboo-ruby-oauth#2]
Trying to work out what exactly the format for audio and image file uploads are with an authenticated post. I need to view an example output, so I can debug the problem with the format of the post. To get a sample post I was hoping to be able to use the samble web app - but it appears to not work:

```
bundle exec ruby audioboo-oauth-webapp.rb
audioboo-oauth-webapp.rb:3:in `require': cannot load such file -- oauth (LoadError)
        from audioboo-oauth-webapp.rb:3:in `<main>'
```

The cli version here does work. Can you advise on how to update this Sinatra demo server to use OAuth2 - or otherwise show me an example HTTP POST request so I can figure out what I need to send. Docs are not that clear.

**Comment by jdelStrother** [comment]
Thanks for the report, will take a look.

**Comment by jdelStrother** [comment]
We've updated the sample code to use OAuth2, let us know if you're still having trouble.
